### ISSUE TITLE
Unable to use 

### ISSUE THREAD

**Issue by SnortsAlot** [SetaSensei/vttes-to-foundry#1]
When opening a new actor to import into - VTTes doesn't present as an option on the title bar.

**Comment by SetaSensei** [comment]
Can you give me more infos such as the Foundry version ?
Can you try disabling all modules except vttes-to-foundry and see if it still does not show ? If it does, what modules are you using ?

**Comment by SnortsAlot** [comment]
Sure - I've updated to your current version; 

I'm on v.8.9 dnd 1.4.2

using Libwrapper & Laptop Form fix. 
without them, same thing.

With the NEW release - its now showing the vttes importer on the title bar, however the link does nothing.

```
Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\Servers\FoundryVTT\Data\modules\vttes-to-foundry\templates\file-picker.hbs'
    at f.<anonymous> (foundry.js:3597)
    at f.value (socket.js:305)
    at f.value (socket.js:228)
    at y.r.emit (index.js:145)
    at y.value (typed-events.js:59)
    at y.value (manager.js:214)
    at n.r.emit (index.js:145)
    at n.value (index.js:120)
    at y.value (manager.js:206)
    at p.r.emit (index.js:145)
```

**Comment by SetaSensei** [comment]
Yes, my bad, I did not correctly add the template file.
The new version fixes that.

**Comment by SnortsAlot** [comment]
![image](https://user-images.githubusercontent.com/60561312/130545846-8f582ca3-7867-4d64-aba3-77ed324de067.png)
Updated, but continued issues.

**Comment by SetaSensei** [comment]
Would you mind sharing the json file you are using ?

**Comment by SnortsAlot** [comment]
actually a collection of such
https://github.com/DMsGuild201/Roll20_resources/tree/master/NPC
https://github.com/DMsGuild201/Roll20_resources/tree/master/Bestiary

Starting with the 

Alain Pious.json
Bargle Strangelove.json
Elinara.json
Hector Hyacinthus.json
Pryshanna.json

none have worked. Looking at them many have remnants from shaped, but do open inside Roll20 still.
[_Alain Pious.zip](https://github.com/SetaSensei/vttes-to-foundry/files/7038951/_Alain.Pious.zip)
