### ISSUE TITLE
Warn the user for unsupported vttes schema version

### ISSUE THREAD

**Issue by SetaSensei** [SetaSensei/vttes-to-foundry#4]
- Linked to https://github.com/SetaSensei/vttes-to-foundry/issues/1

Prevent import from invalid files (any json and schema previous version 3)

**Comment by SnortsAlot** [comment]
Do you have any idea what version(s) of the characters to support, importing w/ vttes and exporting again doesn't create a file you support from my testing. (prior attachment)

**Comment by SetaSensei** [comment]
Schema version 3 and up.

Note that the files you attached do not include any version info and will be rejected by the module.
If you want to check the version, the first property you will see in the JSON will be `"schema_version": 3,`.

Example :

```JSON
{
    "schema_version": 3,
    "type": "character",
    "character": { ...
}}
```

**Comment by SnortsAlot** [comment]
With this character the game containing the characters was confirmed to use 5e by Roll20 charactersheet.
Sheet's directly exported from such are getting the     `"schema_version": 3,` keypair was part of such of the exports, additionaly a new character was made in the game and also tried duplicating a character from prior one.

So attached is a character that was created through duplicate and VTTes exported - it (Roll20) tagged it the schema version. (Though I did try just adding to the alain pious sheet previously provided)

[ln mkdir _Ellen eM'Kaydir_.zip](https://github.com/SetaSensei/vttes-to-foundry/files/7071509/Copy.of.ln.mkdir._Ellen.eM.Kaydir_.zip)

```
Uncaught (in promise) TypeError: Cannot read property 'img' of null
    at PCActorImport.getOverridenClassData (ActorImporter.js:433)
    at PCActorImport.setClass (ActorImporter.js:423)
    at PCActorImport.setActorMainClass (ActorImporter.js:374)
    at PCActorImport.import (PCActor.js:18)
    at async importToActor (actorLib.js:34)
```

or 

```
foundry.js:8666 Error: Required field "name" not present in ItemData
    at ItemData._validateField (data.mjs:361)
    at ItemData.validate (data.mjs:273)
    at new DocumentData (data.mjs:48)
    at new ItemData (data.mjs:793)
    at new Document (document.mjs:46)
    at new BaseItem (documents.mjs:489)
    at new <anonymous> (foundry.js:9199)
    at new Item (foundry.js:14457)
    at new Item5e (entity.js:8)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:8663)
_preCreateDocumentArray @ foundry.js:8666
_createEmbeddedDocuments @ foundry.js:8629
create @ backend.mjs:95
async function (async)
create @ backend.mjs:93
createDocuments @ document.mjs:332
createEmbeddedDocuments @ document.mjs:514
setClass @ ActorImporter.js:424
async function (async)
setClass @ ActorImporter.js:394
setActorMainClass @ ActorImporter.js:374
import @ PCActor.js:18
async function (async)
import @ PCActor.js:11
importToActor @ actorLib.js:34
fReader.onload @ module.js:74
load (async)
actorReadFile @ module.js:72
submit @ foundry.js:20673
_onClickButton @ foundry.js:20636
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
ActorImporter.js:502 Uncaught (in promise) TypeError: Cannot read property 'current' of undefined
    at PCActorImport.getHp (ActorImporter.js:502)
    at PCActorImport.updatePCActorSheet (PCActor.js:102)
    at PCActorImport.import (PCActor.js:38)
    at async importToActor (actorLib.js:34)
```

Seems to suggest that VTTes exports are not just `"schema_version": 3,`  but some other factor as well 
(for your known issues and limitations)

**Comment by SetaSensei** [comment]
Ok. I see the issues in the file.
The class as described is not in the SRD. A custom class creation is *not* implemented. The module searches through the game's compendium. There is another issue with token description.

I'll ask you to create another ticket related to the file you linked. The current issue is to prevent the use of a file in an incorrect format. Other corrections & implementations will be linked to other tickets.

Thanks.
