### ISSUE TITLE
Import not working 

### ISSUE THREAD

**Issue by GrimIcarus** [SetaSensei/vttes-to-foundry#41]
I've tried to upload a json export of VTTES to foundry using this, and got this error

https://pastebin.com/ywv2ZGAX
is my console log 

firefox 106
foundry v10, build 290 (stable)
DnD 5e Fifth edition system 2.0.3
VTTES-to-foundry v0.2.3.4 (according to foundry)

**Comment by GrimIcarus** [comment]
Things Attempted 
Different Browser

**Comment by GrimIcarus** [comment]
Things attempted 
Different browser (Brave, Console log below)
https://pastebin.com/cRuURNhm

Disabled all other modules

Restarted world, may restart entire docker container when i get the chance.

**Comment by SetaSensei** [comment]
Can you also share the character's json file ?

**Comment by SetaSensei** [comment]
Fixed in latest version.
